spring:
  datasource:
    username: sa
    password: password
    url: jdbc:hsqldb:mem:chimera-demo
  jpa:
    generate-ddl: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  data:
    rest:
      base-path: /api/entities

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

tm:
  max-sessions: 100
  debug-enabled: true
  debug-participant-enabled: true

server:
  port: 8086

