
spring:
  data:
    rest:
      base-path: /api/entities
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

management:
  security:
    enabled: false
  contextPath: /admin

tm:
  max-sessions: 100
  debug-enabled: true
  debug-participant-enabled: true

prometheus:
  metrics-collector:
    namespace: boot
    subsystem: actuator

server:
  port: 8086

