
spring:
  data:
    rest:
      base-path: /api/entities

management:
  security:
    enabled: false
  contextPath: /admin

tm:
  max-sessions: 100
  debug-enabled: false
  debug-participant-enabled: false

server:
  port: 8086

